// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgresstore

import (
	"database/sql"
	"time"
)

type Datarange struct {
	ID              sql.NullInt64
	DatasetID       int64
	ObjectKey       string
	MinDatapointKey int64
	MaxDatapointKey int64
	SizeBytes       int64
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Dataset struct {
	ID         sql.NullInt64
	Name       string
	S3BucketID int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type KeysToDelete struct {
	ID          sql.NullInt64
	ObjectKey   string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeleteAfter time.Time
}

type S3Bucket struct {
	ID        sql.NullInt64
	Endpoint  string
	Bucket    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
