// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package postgresstore

import (
	"context"
)

const datasetExists = `-- name: DatasetExists :one
SELECT count(*) > 0 FROM datasets
`

func (q *Queries) DatasetExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, datasetExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
